version: '3.7'

volumes:
  double-take-alpr:

services:
  double-take:
    container_name: double-take-alpr
    image: sch0field9/double-take
    restart: unless-stopped
    volumes:
      - double-take-alpr:/.storage
    ports:
      - 3003:3000
